apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-demo-gateway
spec:
  replicas: 1  # 设置副本数量（可以根据需要调整）
  selector:
    matchLabels:
      app: cloud-demo-gateway
  template:
    metadata:
      labels:
        app: cloud-demo-gateway
    spec:
      containers:
        - name: cloud-demo-gateway
          image: cloud-demo-gateway:v1.0
          ports:
            - containerPort: 7000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
#          env:  # 如果需要环境变量，可以在这里添加
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-demo-gateway
spec:
  selector:
    app: cloud-demo-gateway
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 31000
  type: NodePort

