apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: order
  endpoints:
    - interval: 5s
      port: web
      path: /actuator/prometheus
      scheme: http          # 指定协议
  namespaceSelector:
    matchNames:
      - default